### PR TITLE
:P

### PR DESCRIPTION
**Pull request by foobarbazmeow**
i was bored

### CODE REVIEW

**Comment by leppie** [comment]
What is the purpose here? 36 changed files does not instill confidence :D I see a lot of renames that should have been detected by git, but due to other changes, it chokes. 

Can you do all renames in separate commit, then apply changes in the following commits? 

Also, what is Topshelf?

**Comment by leppie** [comment]
I had a bit more of a look, and I like what you did. Maybe I can just ignore the diff. But tell me about Topshelf.

**Comment by foobarbazmeow** [comment]
:D
I'm too lazy to call InstallUtil. So i'm using Topshelf.
[Topshelf](https://github.com/Topshelf/Topshelf) is a windows service hosting framework.
It's an easiest way to debug windows service (cause it's just a console application). Also it can be configured dozens of parameters.
If you need to install it as a service – run you app with `install` argument.

**Comment by leppie** [comment]
Merged manually. Thanks.

Note: Not running it yet, want to sort out settings so keys can be kept out of the repo.

**Comment by foobarbazmeow** [comment]
YAY

**Pull request closed without merging**
